//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace weather.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weather", Namespace="http://schemas.datacontract.org/2004/07/weather.Web.Models")]
    public partial class Weather : object, System.ComponentModel.INotifyPropertyChanged {
        
        private weather.ServiceReference1.weatherinfo weatherinfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weather.ServiceReference1.weatherinfo weatherinfo {
            get {
                return this.weatherinfoField;
            }
            set {
                if ((object.ReferenceEquals(this.weatherinfoField, value) != true)) {
                    this.weatherinfoField = value;
                    this.RaisePropertyChanged("weatherinfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="weatherinfo", Namespace="http://schemas.datacontract.org/2004/07/weather.Web.Models")]
    public partial class weatherinfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aftertomorrowField;
        
        private string cityField;
        
        private string date_yField;
        
        private string img_title1Field;
        
        private string img_title10Field;
        
        private string img_title11Field;
        
        private string img_title12Field;
        
        private string img_title2Field;
        
        private string img_title3Field;
        
        private string img_title4Field;
        
        private string img_title5Field;
        
        private string img_title6Field;
        
        private string img_title7Field;
        
        private string img_title8Field;
        
        private string img_title9Field;
        
        private string temp1Field;
        
        private string temp2Field;
        
        private string temp3Field;
        
        private string temp4Field;
        
        private string temp5Field;
        
        private string temp6Field;
        
        private string tomorrowField;
        
        private string weather1Field;
        
        private string weather2Field;
        
        private string weather3Field;
        
        private string weather4Field;
        
        private string weather5Field;
        
        private string weather6Field;
        
        private string weekField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aftertomorrow {
            get {
                return this.aftertomorrowField;
            }
            set {
                if ((object.ReferenceEquals(this.aftertomorrowField, value) != true)) {
                    this.aftertomorrowField = value;
                    this.RaisePropertyChanged("aftertomorrow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_y {
            get {
                return this.date_yField;
            }
            set {
                if ((object.ReferenceEquals(this.date_yField, value) != true)) {
                    this.date_yField = value;
                    this.RaisePropertyChanged("date_y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title1 {
            get {
                return this.img_title1Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title1Field, value) != true)) {
                    this.img_title1Field = value;
                    this.RaisePropertyChanged("img_title1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title10 {
            get {
                return this.img_title10Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title10Field, value) != true)) {
                    this.img_title10Field = value;
                    this.RaisePropertyChanged("img_title10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title11 {
            get {
                return this.img_title11Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title11Field, value) != true)) {
                    this.img_title11Field = value;
                    this.RaisePropertyChanged("img_title11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title12 {
            get {
                return this.img_title12Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title12Field, value) != true)) {
                    this.img_title12Field = value;
                    this.RaisePropertyChanged("img_title12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title2 {
            get {
                return this.img_title2Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title2Field, value) != true)) {
                    this.img_title2Field = value;
                    this.RaisePropertyChanged("img_title2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title3 {
            get {
                return this.img_title3Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title3Field, value) != true)) {
                    this.img_title3Field = value;
                    this.RaisePropertyChanged("img_title3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title4 {
            get {
                return this.img_title4Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title4Field, value) != true)) {
                    this.img_title4Field = value;
                    this.RaisePropertyChanged("img_title4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title5 {
            get {
                return this.img_title5Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title5Field, value) != true)) {
                    this.img_title5Field = value;
                    this.RaisePropertyChanged("img_title5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title6 {
            get {
                return this.img_title6Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title6Field, value) != true)) {
                    this.img_title6Field = value;
                    this.RaisePropertyChanged("img_title6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title7 {
            get {
                return this.img_title7Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title7Field, value) != true)) {
                    this.img_title7Field = value;
                    this.RaisePropertyChanged("img_title7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title8 {
            get {
                return this.img_title8Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title8Field, value) != true)) {
                    this.img_title8Field = value;
                    this.RaisePropertyChanged("img_title8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img_title9 {
            get {
                return this.img_title9Field;
            }
            set {
                if ((object.ReferenceEquals(this.img_title9Field, value) != true)) {
                    this.img_title9Field = value;
                    this.RaisePropertyChanged("img_title9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp1 {
            get {
                return this.temp1Field;
            }
            set {
                if ((object.ReferenceEquals(this.temp1Field, value) != true)) {
                    this.temp1Field = value;
                    this.RaisePropertyChanged("temp1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp2 {
            get {
                return this.temp2Field;
            }
            set {
                if ((object.ReferenceEquals(this.temp2Field, value) != true)) {
                    this.temp2Field = value;
                    this.RaisePropertyChanged("temp2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp3 {
            get {
                return this.temp3Field;
            }
            set {
                if ((object.ReferenceEquals(this.temp3Field, value) != true)) {
                    this.temp3Field = value;
                    this.RaisePropertyChanged("temp3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp4 {
            get {
                return this.temp4Field;
            }
            set {
                if ((object.ReferenceEquals(this.temp4Field, value) != true)) {
                    this.temp4Field = value;
                    this.RaisePropertyChanged("temp4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp5 {
            get {
                return this.temp5Field;
            }
            set {
                if ((object.ReferenceEquals(this.temp5Field, value) != true)) {
                    this.temp5Field = value;
                    this.RaisePropertyChanged("temp5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp6 {
            get {
                return this.temp6Field;
            }
            set {
                if ((object.ReferenceEquals(this.temp6Field, value) != true)) {
                    this.temp6Field = value;
                    this.RaisePropertyChanged("temp6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tomorrow {
            get {
                return this.tomorrowField;
            }
            set {
                if ((object.ReferenceEquals(this.tomorrowField, value) != true)) {
                    this.tomorrowField = value;
                    this.RaisePropertyChanged("tomorrow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather1 {
            get {
                return this.weather1Field;
            }
            set {
                if ((object.ReferenceEquals(this.weather1Field, value) != true)) {
                    this.weather1Field = value;
                    this.RaisePropertyChanged("weather1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather2 {
            get {
                return this.weather2Field;
            }
            set {
                if ((object.ReferenceEquals(this.weather2Field, value) != true)) {
                    this.weather2Field = value;
                    this.RaisePropertyChanged("weather2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather3 {
            get {
                return this.weather3Field;
            }
            set {
                if ((object.ReferenceEquals(this.weather3Field, value) != true)) {
                    this.weather3Field = value;
                    this.RaisePropertyChanged("weather3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather4 {
            get {
                return this.weather4Field;
            }
            set {
                if ((object.ReferenceEquals(this.weather4Field, value) != true)) {
                    this.weather4Field = value;
                    this.RaisePropertyChanged("weather4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather5 {
            get {
                return this.weather5Field;
            }
            set {
                if ((object.ReferenceEquals(this.weather5Field, value) != true)) {
                    this.weather5Field = value;
                    this.RaisePropertyChanged("weather5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weather6 {
            get {
                return this.weather6Field;
            }
            set {
                if ((object.ReferenceEquals(this.weather6Field, value) != true)) {
                    this.weather6Field = value;
                    this.RaisePropertyChanged("weather6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string week {
            get {
                return this.weekField;
            }
            set {
                if ((object.ReferenceEquals(this.weekField, value) != true)) {
                    this.weekField = value;
                    this.RaisePropertyChanged("week");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWeatherService")]
    public interface IWeatherService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWeatherService/DoWork", ReplyAction="http://tempuri.org/IWeatherService/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWeatherService/GetWeatherInfo", ReplyAction="http://tempuri.org/IWeatherService/GetWeatherInfoResponse")]
        System.IAsyncResult BeginGetWeatherInfo(string cityName, System.AsyncCallback callback, object asyncState);
        
        weather.ServiceReference1.Weather EndGetWeatherInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWeatherService/GetAirInfo", ReplyAction="http://tempuri.org/IWeatherService/GetAirInfoResponse")]
        System.IAsyncResult BeginGetAirInfo(System.AsyncCallback callback, object asyncState);
        
        string EndGetAirInfo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServiceChannel : weather.ServiceReference1.IWeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWeatherInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWeatherInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public weather.ServiceReference1.Weather Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((weather.ServiceReference1.Weather)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAirInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAirInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<weather.ServiceReference1.IWeatherService>, weather.ServiceReference1.IWeatherService {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWeatherInfoDelegate;
        
        private EndOperationDelegate onEndGetWeatherInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetWeatherInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAirInfoDelegate;
        
        private EndOperationDelegate onEndGetAirInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAirInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WeatherServiceClient() {
        }
        
        public WeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<GetWeatherInfoCompletedEventArgs> GetWeatherInfoCompleted;
        
        public event System.EventHandler<GetAirInfoCompletedEventArgs> GetAirInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult weather.ServiceReference1.IWeatherService.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void weather.ServiceReference1.IWeatherService.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((weather.ServiceReference1.IWeatherService)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((weather.ServiceReference1.IWeatherService)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult weather.ServiceReference1.IWeatherService.BeginGetWeatherInfo(string cityName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWeatherInfo(cityName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        weather.ServiceReference1.Weather weather.ServiceReference1.IWeatherService.EndGetWeatherInfo(System.IAsyncResult result) {
            return base.Channel.EndGetWeatherInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetWeatherInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cityName = ((string)(inValues[0]));
            return ((weather.ServiceReference1.IWeatherService)(this)).BeginGetWeatherInfo(cityName, callback, asyncState);
        }
        
        private object[] OnEndGetWeatherInfo(System.IAsyncResult result) {
            weather.ServiceReference1.Weather retVal = ((weather.ServiceReference1.IWeatherService)(this)).EndGetWeatherInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWeatherInfoCompleted(object state) {
            if ((this.GetWeatherInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWeatherInfoCompleted(this, new GetWeatherInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWeatherInfoAsync(string cityName) {
            this.GetWeatherInfoAsync(cityName, null);
        }
        
        public void GetWeatherInfoAsync(string cityName, object userState) {
            if ((this.onBeginGetWeatherInfoDelegate == null)) {
                this.onBeginGetWeatherInfoDelegate = new BeginOperationDelegate(this.OnBeginGetWeatherInfo);
            }
            if ((this.onEndGetWeatherInfoDelegate == null)) {
                this.onEndGetWeatherInfoDelegate = new EndOperationDelegate(this.OnEndGetWeatherInfo);
            }
            if ((this.onGetWeatherInfoCompletedDelegate == null)) {
                this.onGetWeatherInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWeatherInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetWeatherInfoDelegate, new object[] {
                        cityName}, this.onEndGetWeatherInfoDelegate, this.onGetWeatherInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult weather.ServiceReference1.IWeatherService.BeginGetAirInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAirInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string weather.ServiceReference1.IWeatherService.EndGetAirInfo(System.IAsyncResult result) {
            return base.Channel.EndGetAirInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetAirInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((weather.ServiceReference1.IWeatherService)(this)).BeginGetAirInfo(callback, asyncState);
        }
        
        private object[] OnEndGetAirInfo(System.IAsyncResult result) {
            string retVal = ((weather.ServiceReference1.IWeatherService)(this)).EndGetAirInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAirInfoCompleted(object state) {
            if ((this.GetAirInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAirInfoCompleted(this, new GetAirInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAirInfoAsync() {
            this.GetAirInfoAsync(null);
        }
        
        public void GetAirInfoAsync(object userState) {
            if ((this.onBeginGetAirInfoDelegate == null)) {
                this.onBeginGetAirInfoDelegate = new BeginOperationDelegate(this.OnBeginGetAirInfo);
            }
            if ((this.onEndGetAirInfoDelegate == null)) {
                this.onEndGetAirInfoDelegate = new EndOperationDelegate(this.OnEndGetAirInfo);
            }
            if ((this.onGetAirInfoCompletedDelegate == null)) {
                this.onGetAirInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAirInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAirInfoDelegate, null, this.onEndGetAirInfoDelegate, this.onGetAirInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override weather.ServiceReference1.IWeatherService CreateChannel() {
            return new WeatherServiceClientChannel(this);
        }
        
        private class WeatherServiceClientChannel : ChannelBase<weather.ServiceReference1.IWeatherService>, weather.ServiceReference1.IWeatherService {
            
            public WeatherServiceClientChannel(System.ServiceModel.ClientBase<weather.ServiceReference1.IWeatherService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginGetWeatherInfo(string cityName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cityName;
                System.IAsyncResult _result = base.BeginInvoke("GetWeatherInfo", _args, callback, asyncState);
                return _result;
            }
            
            public weather.ServiceReference1.Weather EndGetWeatherInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                weather.ServiceReference1.Weather _result = ((weather.ServiceReference1.Weather)(base.EndInvoke("GetWeatherInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAirInfo(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAirInfo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetAirInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetAirInfo", _args, result)));
                return _result;
            }
        }
    }
}
